// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordadder.proto

package recordadder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Queue struct {
	Requests             []*AddRecordRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	ProcessedRecords     int32               `protobuf:"varint,2,opt,name=processed_records,json=processedRecords,proto3" json:"processed_records,omitempty"`
	LastAdditionDate     int64               `protobuf:"varint,3,opt,name=last_addition_date,json=lastAdditionDate,proto3" json:"last_addition_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Queue) Reset()         { *m = Queue{} }
func (m *Queue) String() string { return proto.CompactTextString(m) }
func (*Queue) ProtoMessage()    {}
func (*Queue) Descriptor() ([]byte, []int) {
	return fileDescriptor_365a0310624e2f56, []int{0}
}

func (m *Queue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Queue.Unmarshal(m, b)
}
func (m *Queue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Queue.Marshal(b, m, deterministic)
}
func (m *Queue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Queue.Merge(m, src)
}
func (m *Queue) XXX_Size() int {
	return xxx_messageInfo_Queue.Size(m)
}
func (m *Queue) XXX_DiscardUnknown() {
	xxx_messageInfo_Queue.DiscardUnknown(m)
}

var xxx_messageInfo_Queue proto.InternalMessageInfo

func (m *Queue) GetRequests() []*AddRecordRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *Queue) GetProcessedRecords() int32 {
	if m != nil {
		return m.ProcessedRecords
	}
	return 0
}

func (m *Queue) GetLastAdditionDate() int64 {
	if m != nil {
		return m.LastAdditionDate
	}
	return 0
}

type AddRecordRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cost                 int32    `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Folder               int32    `protobuf:"varint,3,opt,name=folder,proto3" json:"folder,omitempty"`
	AccountingYear       int32    `protobuf:"varint,4,opt,name=accounting_year,json=accountingYear,proto3" json:"accounting_year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordRequest) Reset()         { *m = AddRecordRequest{} }
func (m *AddRecordRequest) String() string { return proto.CompactTextString(m) }
func (*AddRecordRequest) ProtoMessage()    {}
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_365a0310624e2f56, []int{1}
}

func (m *AddRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordRequest.Unmarshal(m, b)
}
func (m *AddRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordRequest.Marshal(b, m, deterministic)
}
func (m *AddRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordRequest.Merge(m, src)
}
func (m *AddRecordRequest) XXX_Size() int {
	return xxx_messageInfo_AddRecordRequest.Size(m)
}
func (m *AddRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordRequest proto.InternalMessageInfo

func (m *AddRecordRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddRecordRequest) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *AddRecordRequest) GetFolder() int32 {
	if m != nil {
		return m.Folder
	}
	return 0
}

func (m *AddRecordRequest) GetAccountingYear() int32 {
	if m != nil {
		return m.AccountingYear
	}
	return 0
}

type AddRecordResponse struct {
	ExpectedAdditionDate int64    `protobuf:"varint,1,opt,name=expected_addition_date,json=expectedAdditionDate,proto3" json:"expected_addition_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordResponse) Reset()         { *m = AddRecordResponse{} }
func (m *AddRecordResponse) String() string { return proto.CompactTextString(m) }
func (*AddRecordResponse) ProtoMessage()    {}
func (*AddRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_365a0310624e2f56, []int{2}
}

func (m *AddRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordResponse.Unmarshal(m, b)
}
func (m *AddRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordResponse.Marshal(b, m, deterministic)
}
func (m *AddRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordResponse.Merge(m, src)
}
func (m *AddRecordResponse) XXX_Size() int {
	return xxx_messageInfo_AddRecordResponse.Size(m)
}
func (m *AddRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordResponse proto.InternalMessageInfo

func (m *AddRecordResponse) GetExpectedAdditionDate() int64 {
	if m != nil {
		return m.ExpectedAdditionDate
	}
	return 0
}

func init() {
	proto.RegisterType((*Queue)(nil), "recordadder.Queue")
	proto.RegisterType((*AddRecordRequest)(nil), "recordadder.AddRecordRequest")
	proto.RegisterType((*AddRecordResponse)(nil), "recordadder.AddRecordResponse")
}

func init() { proto.RegisterFile("recordadder.proto", fileDescriptor_365a0310624e2f56) }

var fileDescriptor_365a0310624e2f56 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0x36, 0xfd, 0x43, 0xa7, 0x50, 0xdb, 0x41, 0xca, 0x22, 0x28, 0x65, 0x2f, 0x16, 0x94, 0x1e,
	0xaa, 0x17, 0x8f, 0x05, 0x41, 0x04, 0x2f, 0x46, 0x2f, 0x9e, 0x96, 0x98, 0x19, 0x25, 0x50, 0x36,
	0x6b, 0x92, 0xf5, 0xe7, 0x61, 0x7c, 0x00, 0xdf, 0x52, 0x9a, 0xad, 0xeb, 0x52, 0xd0, 0x8b, 0xb7,
	0xcc, 0x7c, 0xf3, 0xfd, 0xcc, 0x10, 0x18, 0x39, 0xd6, 0xd6, 0x91, 0x22, 0x62, 0x37, 0x2b, 0x9c,
	0x0d, 0x16, 0xfb, 0x8d, 0x56, 0xfa, 0x21, 0xa0, 0x7b, 0x53, 0x72, 0xc9, 0x78, 0x0e, 0xdb, 0x8e,
	0x9f, 0x4b, 0xf6, 0xc1, 0x27, 0x62, 0xd2, 0x9e, 0xf6, 0xe7, 0x07, 0xb3, 0x26, 0x79, 0x41, 0x24,
	0x63, 0x29, 0xab, 0x29, 0x59, 0x8f, 0xe3, 0x31, 0x8c, 0x0a, 0x67, 0x35, 0x7b, 0xcf, 0x94, 0x55,
	0x1c, 0x9f, 0xb4, 0x26, 0x62, 0xda, 0x95, 0xc3, 0x1a, 0xa8, 0xc8, 0x1e, 0x4f, 0x00, 0x97, 0xca,
	0x87, 0x4c, 0x11, 0x99, 0x60, 0x6c, 0x9e, 0x91, 0x0a, 0x9c, 0xb4, 0x27, 0x62, 0xda, 0x96, 0xc3,
	0x15, 0xb2, 0x58, 0x03, 0x17, 0x2a, 0x70, 0xfa, 0x0a, 0xc3, 0x4d, 0x63, 0x1c, 0x40, 0xcb, 0x50,
	0x22, 0xa2, 0x7e, 0xcb, 0x10, 0x22, 0x74, 0xb4, 0xf5, 0x61, 0xed, 0x18, 0xdf, 0x38, 0x86, 0xde,
	0xa3, 0x5d, 0x12, 0xbb, 0xa8, 0xdc, 0x95, 0xeb, 0x0a, 0x8f, 0x60, 0x57, 0x69, 0x6d, 0xcb, 0x3c,
	0x98, 0xfc, 0x29, 0x7b, 0x67, 0xe5, 0x92, 0x4e, 0x1c, 0x18, 0xfc, 0xb4, 0xef, 0x59, 0xb9, 0xf4,
	0x0a, 0x46, 0x0d, 0x63, 0x5f, 0xd8, 0xdc, 0x33, 0x9e, 0xc1, 0x98, 0xdf, 0x0a, 0xd6, 0x81, 0x69,
	0x23, 0xbf, 0x88, 0xf9, 0xf7, 0xbe, 0xd1, 0xe6, 0x0e, 0xf3, 0x4f, 0xd1, 0x58, 0xe2, 0x96, 0xdd,
	0x8b, 0xd1, 0x8c, 0xd7, 0xb0, 0x53, 0xf7, 0xf0, 0xef, 0x4b, 0xef, 0x1f, 0xfe, 0x06, 0x57, 0xb1,
	0xd2, 0x2d, 0xbc, 0x84, 0xce, 0xdd, 0xea, 0x34, 0xff, 0x15, 0x7a, 0xe8, 0xc5, 0x3f, 0x72, 0xfa,
	0x15, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x07, 0xa8, 0xa1, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddRecordServiceClient is the client API for AddRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddRecordServiceClient interface {
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	Test(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
}

type addRecordServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddRecordServiceClient(cc *grpc.ClientConn) AddRecordServiceClient {
	return &addRecordServiceClient{cc}
}

func (c *addRecordServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, "/recordadder.AddRecordService/AddRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addRecordServiceClient) Test(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, "/recordadder.AddRecordService/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddRecordServiceServer is the server API for AddRecordService service.
type AddRecordServiceServer interface {
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	Test(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
}

func RegisterAddRecordServiceServer(s *grpc.Server, srv AddRecordServiceServer) {
	s.RegisterService(&_AddRecordService_serviceDesc, srv)
}

func _AddRecordService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddRecordServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordadder.AddRecordService/AddRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddRecordServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddRecordService_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddRecordServiceServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordadder.AddRecordService/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddRecordServiceServer).Test(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddRecordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordadder.AddRecordService",
	HandlerType: (*AddRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRecord",
			Handler:    _AddRecordService_AddRecord_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _AddRecordService_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordadder.proto",
}
